#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`


In [2]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [12]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [10]:
null_vector_2 = np.zeros(10)
null_vector_2[5] = 1

print(null_vector_2)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [13]:
vector_3 = np.arange(10,50)
print(vector_3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [36]:
vector_4 = np.arange(0,9).reshape(3,3)

print(vector_4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [62]:
#elements = [1,2,0,0,4,0]
#for i in elements:
 #   np.nonzero(i)
#print(i)

non_zero = np.nonzero([1,2,0,0,4,0])

print(non_zero)

(array([0, 1, 4]),)


#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [35]:
matrix = np.eye(3,3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`



random = np.random.random((10,10))


min = np.min(random)
max = np.max(random)

print(min)

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`


In [39]:
random_vector = np.random.random(30)
random_vector.mean()

0.49887621901691853

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [71]:
matrix_values = np.diag([1,2,3,4], -1)

print(matrix_values)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [85]:
random_matrix = np.random.random((5,5))

mean = np.mean(random_matrix)

std = np.std(random_matrix)

random_matrix_2 = (random_matrix - mean)/std

print(random_matrix_2)



[[ 0.89896907  0.86021059 -0.78745454  0.28830708  0.34680288]
 [ 1.32544967  0.38324563 -1.78835679 -1.62508568  1.02663306]
 [ 1.35105419  0.28040214 -0.95133795 -0.62827305  0.91853978]
 [-0.19191147  1.12495415 -0.05450519  0.42895239  1.17143498]
 [-1.34559176 -1.66850079 -1.40238556  0.44386656 -0.4054194 ]]


#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`


In [55]:
arr_1 = np.random.random(10)

arr_2 = np.random.random(10)

common_value = np.intersect1d(arr_1,arr_2)


print(common_value)


[]


#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [49]:
size = np.random.random(10)
size_two = np.sort(size)

print(size)


[0.76090386 0.23739779 0.51694149 0.96482897 0.70146803 0.88562273
 0.90802659 0.61181201 0.41008697 0.65322328]


#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [99]:
create = np.random.random(10)

replace = np.argmax(create)

create[replace] = 0

print(create)

[0.36149008 0.74235968 0.87591787 0.79576702 0.38192807 0.58253662
 0.59239062 0.64276993 0.         0.52922741]


#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [108]:
a = np.random.rand(1, 10)
b = a - a.mean(axis=1, keepdims=True)



print(b)

[[-0.01838865  0.09382554 -0.20042271  0.24554563  0.08605355 -0.45944424
  -0.27927887  0.11847465  0.15476517  0.25886993]]


#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`